#!/usr/bin/env ruby
# frozen_string_literal: true

require 'pp'
require 'optparse'
require 'socket'

SCRIPT_DIR = File.dirname(File.realpath($PROGRAM_NAME))
PREPROCESS = File.join(SCRIPT_DIR, 'preprocess')

$servername = Socket.gethostname
$dry_run = false
$port = 25
$print_raw = false
YELLOW = "\033[33m"
NORMAL = "\033[0m"
optpars = OptionParser.new { |opts|
	examples = [
		['Check if Mail works (+IP reverse lookup, + IP Blacklist)', "someone@#{$servername}", 'someone@server',
			'examples/valid.eml'],
		['Check for open relay', "someone@#{$servername}", 'name.lastname@your.external.domain.com', 'examples/valid.eml'],
		['Check if SPF pass is recognized', 'someone@pass.mail.mgm-sp.team', 'someone@server', 'examples/spf-pass.eml'],
		['Check if SPF hardfail (-all) is rejected', 'someone@hardfail.mail.mgm-sp.team', 'someone@server',
			'examples/spf-hardfail.eml'],
		['Check if SPF softfail (~all) is handled', 'someone@softfail.mail.mgm-sp.team', 'someone@server',
			'examples/spf-softfail.eml'],
		['Check if SPF neutral (?all) is handled', 'someone@neutral.mail.mgm-sp.team', 'someone@server',
			'examples/spf-neutral.eml'],
		['Check if From-Address can be bullshit', "someone@#{$servername}", 'someone@server', 'examples/invalid-from.eml'],
		['Check if DMARC reject is checked', "someone@#{$servername}", 'someone@server', 'examples/dmarc-reject.eml'],
		['Check if DMARC quarantine is checked', "someone@#{$servername}", 'someone@server', 'examples/dmarc-quarantine.eml'],
		['Check if DKIM is checked', "someone@#{$servername}", 'someone@server', 'examples/dkim-reject.eml'],
		['Check if SPF pass without alignment and invalid DKIM triggers DMARC reject', 'someone@pass.mail.mgm-sp.team',
			'someone@server', 'examples/spf-pass-dkim-fail.eml'],
		['Check if SPF pass without alignment and missing DKIM triggers DMARC reject', 'someone@pass.mail.mgm-sp.team',
			'someone@server', 'examples/dmarc-reject.eml'],
		['Check if receipient has a virus scanner in place', "someone@#{$servername}", 'someone@server',
			'examples/eicar.eml']
	]
	examples_text = examples.each_with_index.map { |(desc, from, to, file), i|
		"#{YELLOW}#{i + 1}. #{desc}#{NORMAL}\n\t #{File.basename($PROGRAM_NAME)} <server> #{from} #{to} #{file}"
	}.join("\n")
	opts.banner = <<~USAGE
		Usage: #{File.basename($PROGRAM_NAME)} [options] <server> [<mail_from> [<rcpt_to> [mailfile]]]
		Ex.:
		#{examples_text}
	USAGE
	opts.separator 'Options:'

	opts.on('--helo <servername>', "Use <servername> in HELO instead of #{$servername}") { |string|
		$servername = string
	}

	opts.on('--port <port>', "Use <port> instead of #{$port}") { |integer|
		$port = integer.to_i
	}

	opts.on('--print-raw', 'print raw characters like \\n in output') { |bool|
		$print_raw = bool
	}

	opts.on('--dry-run', 'do not execute commands') { |bool|
		$dry_run = bool
	}

	opts.on('-h', '--help', 'show this message') {
		puts opts
		exit
	}
}

begin
	optpars.parse!
rescue StandardError => e
	puts optpars
	raise e
end

class DummyTCPSocket
	def self.open(server, port)
		puts "openssl s_client -starttls smtp -servername #{server} -connect #{server}:#{port} -crlf -quiet"
		DummyTCPSocket.new
	end

	def gets
		'250 DRY-RUN-OK'
	end

	def puts(s); end

	def close; end
end

class SMTP
	def initialize(server)
		@server = server
		if $dry_run
			@s = DummyTCPSocket.open(@server, $port)
		else
			@s = TCPSocket.open(@server, $port)
		end
		puts "$ nc #{@server} #{$port}"
		banner = @s.gets
		puts banner
		exit if banner.scan(/^(\d\d\d)(.*)$/).flatten[0].to_i >= 300
		exit if send_wait("HELO #{$servername}")[0] != 250
	end

	def send_wait(cmd)
		puts cmd
		send("#{cmd}\r\n")
		result = @s.gets
		puts result
		ret = result.scan(/^(\d\d\d)(.*)$/).flatten
		ret[0] = ret[0].to_i
		ret
	end

	def send(cmd)
		@s.puts(cmd)
	end

	def close
		@s.close
	end

	def renew
		@s.close
		initialize(@server)
	end
end

if ARGV[0]
	server = ARGV[0]
else
	puts optpars
	exit
end
s = SMTP.new(server)

exit unless ARGV[1]
exit if s.send_wait("MAIL FROM: <#{ARGV[1]}>")[0] >= 400
exit unless ARGV[2]
exit if s.send_wait("RCPT TO: <#{ARGV[2]}>")[0] >= 400
exit unless ARGV[3]
exit if s.send_wait('DATA')[0] >= 400
IO.popen([PREPROCESS, '--replace', "from=#{ARGV[1]}", '--replace', "to=#{ARGV[2]}", ARGV[3]], 'r') { |pipe|
	pipe.each_line { |line|
		puts($print_raw ? line.inspect[1..-2] : line)
		s.send(line)
	}
}
abort 'preprocess failed' unless $CHILD_STATUS.success?
s.send_wait('.')
s.send_wait('QUIT')
s.close
